name: ci / core

on:
  push: {}
  schedule:
    - cron: '13 * 3,4,5 * *'

jobs:
  test-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true
      - run: go mod download -x
      - run: go install gotest.tools/gotestsum@7f0dfd73d2c769fdc8c6c5fc3b62c6eec94ebb04

      - run: mkdir -p /home/runner/reports
      - uses: actions/cache@v3
        with:
          path: /home/runner/reports
          key: read-go-test-reports-${{ github.run_number }}
          restore-keys: go-test-reports-

      - name: build matrix
        id: build
        run: |
          echo -n "::set-output name=buckets::"
          go list ./... | gotestsum tool ci-matrix --debug --dir=/home/runner/reports
    outputs:
      buckets: ${{ steps.build.outputs.buckets }}


  test:
    needs: test-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bucket: [0, 1, 2, 3]
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: password123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
          cache: true

      - run: go mod download -x
      - run: go install gotest.tools/gotestsum@v1.8.2

      - name: go test
        run: |
          buckets='${{needs.test-matrix.outputs.buckets}}'
          pkgs=$(echo $buckets | jq -r '.["${{matrix.bucket}}"]')

          echo Buckets; echo $buckets
          echo Packages; echo $pkgs

          mkdir -p /home/runner/reports
          ~/go/bin/gotestsum -ftestname \
              --jsonfile=/home/runner/reports/test-run-${{github.run_number}}-${{matrix.bucket}}.log \
              -- -race $pkgs

        env:
          POSTGRESQL_CONNECTION: "host=localhost port=5432 user=postgres dbname=postgres password=password123"

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: /home/runner/reports/*.log
          retention-days: 5

      - name: Check that tests leave a clean git checkout
        run: |
          # show and check changes to committed files
          git diff --exit-code
          # show and check for uncommitted files
          git status --short; [[ "$(git status --short)" == "" ]]

  test-collect-reports:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: /home/runner/reports
          key: go-test-reports-${{ github.run_number }}
          restore-keys: go-test-reports-
      - uses: actions/download-artifact@v3
        with:
          path: /home/runner/reports
      - run: ls -lhR /home/runner/reports
